### ISSUE TITLE
Writing to `Cursor<&mut Vec<u8>>` doesn't grow the `Vec`

### ISSUE THREAD

**Issue by Serial-ATA** [wcampbell0x2a/no-std-io2#1]
Hello!

I'm trying to use [`DekuContainerWrite::to_bytes()`](https://docs.rs/deku/latest/deku/trait.DekuContainerWrite.html#method.to_bytes) in `no_std`. That method uses `Cursor<&mut Vec<u8>>::write()` internally with an empty `Vec`:

https://github.com/sharksforarms/deku/blob/8b1f5af4dbe082007a6c807871f955e5993a54c6/src/lib.rs#L518-L525

This works fine when using `std`, as the impl will grow the `Vec`:

https://doc.rust-lang.org/stable/src/std/io/impls.rs.html#413-416

Using the `no-std-io` impl though, it will immediately error with `WriteZero`, since it can't write to a zero-length `Vec`:

https://github.com/wcampbell0x2a/no-std-io2/blob/61baa943b3f84c73c3d958be26c1cedf9838c8f3/src/io/cursor.rs#L275-L285

**Comment by wcampbell0x2a** [comment]
I added a commit that should fix this, lmk if you find anything else! https://github.com/wcampbell0x2a/no-std-io2/pull/2/commits/7050eef20191899cfdca9e2076e61d08aec0b8c1

**Comment by Serial-ATA** [comment]
Thanks for the quick fix! All my tests are passing now. :)
